apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ekube.fullname" . }}
  labels:
    {{- include "ekube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ekube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ekube.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ekube.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "golang:1.13"
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              cd /src/deployments/submodules/ekube
              while true; do
                go run -mod vendor ./main.go
              done
          volumeMounts:
            - mountPath: /var/vault
              name: secrets
            - mountPath: /src
              name: project-source
            - mountPath: /app
              name: go-app
            - mountPath: /cache
              name: go-cache
            - mountPath: /tmp
              name: go-build
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SECRETS_PATH
              value: "/var/vault"
            - name: SECRETS_FILE
              value: {{ .Values.ekube.SecretsFileName }}
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: MYSQL_SCHEMA
              value: {{ .Values.Database.Schema | quote}}
            - name: MYSQL_HOST
              value: {{ .Values.Database.Host | quote}}
            - name: MYSQL_PORT
              value: {{ .Values.Database.Port | quote}}
            - name: GOCACHE
              value: /cache
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /ready*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: secrets
          configMap:
            name: {{ template "ekube.fullname" . }}-secrets
        - name: project-source
          hostPath:
            path: {{ .Values.ekube.Volumes.ProjectSource }}
        - name: go-cache
          emptyDir: {}
        - name: go-app
          emptyDir: {}
        - name: go-build
          emptyDir: {}

