apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-secrets
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
data:
  secrets.json: |
    {{ .Values.Secrets | toJson | indent 4 }}
