apiVersion: v1
kind: Service
metadata:
  name: {{ include "ekube.fullname" . }}
  labels:
    {{- include "ekube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7777
      protocol: TCP
      name: http
  selector:
    {{- include "ekube.selectorLabels" . | nindent 4 }}
